In [1]:
from __init__ import *
from read_tfrecords import *


In [3]:
dataset = load_dataset([file_path0, file_path1, file_path2, file_path3])
ds_size = sum(1 for _ in dataset)
print('Number of examples', ds_size)


size 800


In [10]:
for song in dataset.take(1):
    print(song)
    print('MFCC shape', song[0].shape)
    print('VAD shape', song[1].shape)

(<tf.Tensor: shape=(13, 323), dtype=float32, numpy=
array([[-155.17055  , -158.98366  , -163.13234  , ...,  -72.96555  ,
         -84.9091   ,  -62.92753  ],
       [  99.1558   ,   97.957504 ,  101.321655 , ...,   79.96465  ,
          75.07255  ,  118.89933  ],
       [ -13.6925535,  -17.695889 ,  -14.263147 , ...,   38.364212 ,
          39.44096  ,    4.8555803],
       ...,
       [ -21.740513 ,  -19.947079 ,  -14.766667 , ...,  -10.251581 ,
         -13.638647 ,  -16.623444 ],
       [  -8.620213 ,   -9.989223 ,   -2.4945712, ...,   -3.563071 ,
          -4.4792986,   -7.765592 ],
       [ -23.119873 ,  -19.910982 ,  -24.13578  , ...,  -16.961184 ,
         -20.201849 ,  -15.877959 ]], dtype=float32)>, <tf.Tensor: shape=(), dtype=float32, numpy=0.7367468>)
MFCC shape (13, 323)
VAD shape ()
